; Temporary alternate PlatformIO config to avoid Windows file locking in .pio/build

[platformio]
default_envs = cardputer_adv
build_dir = .pio/build_alt

[env:cardputer_adv]
platform  = espressif32@6.7.0
board     = m5stack-stamps3
framework = arduino

upload_speed    = 921600
monitor_speed   = 115200
monitor_encoding = utf-8
monitor_filters = esp32_exception_decoder

board_build.mcu          = esp32s3
board_build.f_cpu        = 240000000L
board_build.embed_files  = media/ScreenTitle_boot.jpg
board_build.flash_mode   = dio
board_build.flash_size   = 8MB
board_build.partitions   = huge_app.csv
board_upload.flash_size  = 8MB

build_flags =
    -DESP32S3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUINO_LOOP_TASK_STACK_SIZE=16384
    -DBOARD_HAS_PSRAM=0
    -O2

lib_deps =
    m5stack/M5Cardputer @ ^1.0.2

lib_extra_dirs = lib

[env:cardputer_v11]
extends    = env:cardputer_adv
build_flags =
    ${env:cardputer_adv.build_flags}
    -DCARDPUTER_V11
